### ISSUE TITLE
Simulation unable to launch

### ISSUE THREAD

**Issue by EliasTDam** [lbr-stack/lbr_fri_ros2_stack#124]
Me and my group are using this package. They installed it a couple of weeks ago, and have no issues whatsoever. I however, have tried installing it since yesterday, on a fresh install of Ubuntu and ROS2 Humble, and can't get the simulation to launch. It is from the quick start guide. I try to run the command:

_source install/setup.bash
ros2 launch lbr_bringup bringup.launch.py \
    model:=iiwa7 # [iiwa7, iiwa14, med7, med14] \
    sim:=true # [true, false] \
    rviz:=true # [true, false] \
    moveit:=true # [true, false]_
    
But I get the error:

_[INFO] [launch]: All log files can be found below /home/elias/.ros/log/2023-10-05-10-50-39-318455-ROS2-Host-50919
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): LBRMoveGroupMixin.moveit_configs_builder() missing 1 required positional argument: 'base_frame'
sim:=true: command not found
rviz:=true: command not found
moveit:=true: command not found_

Is this an issue that has been introduced lately, or is something wrong on my side?

**Comment by mhubii** [comment]
Hi @EliasTDam , sorry for the inconvenience. We started namespacing the system and there is an issue with Gazebo.

Try checkout the `dev-humble-v1.3.0-beta-gz-namespace` branch. This will solve your issue. It will be merged soon.

Please let me know if it helps.

**Comment by mhubii** [comment]
Linking #123

**Comment by EliasTDam** [comment]
Thank you very much! I'll definitely try that then

**Comment by mhubii** [comment]
Please re-open in case it doesn't solve the issue and thank you for the feedback !

**Comment by EliasTDam** [comment]
The simulation now launches, so it seems to have resolved the issue. Thanks!

**Comment by mhubii** [comment]
Re-open for visibility until merge of #123

**Comment by mhubii** [comment]
done
