### ISSUE TITLE
Incorrect link `lbr_link_ee`, it appears inside the mesh.

### ISSUE THREAD

**Issue by ardiya** [lbr-stack/lbr_fri_ros2_stack#125]
Dear Maintainers,

I'm currently using the [noetic](https://github.com/lbr-stack/lbr_fri_ros2_stack/tree/noetic) branch, and I am having troubles with the iiwa14.urdf as the `lbr_link_ee` appears inside the mesh, as shown in the image below
 
![Ubuntu-2023-10-16-16-41-03](https://github.com/lbr-stack/lbr_fri_ros2_stack/assets/1798412/48a6c835-fae2-452c-bf28-82dbd91dc2f9)

I'm expecting the `lbr_link_ee` to appears at the end effector tip.

I tried comparing it to iiwa_stack and noticed the https://github.com/IFL-CAMP/iiwa_stack/blob/master/iiwa_description/urdf/iiwa14.xacro#L332-L336 xyz="0 0 0.045" as opposed to xyz="0 0 0.035" in lbr_fri_ros_stack.

Is there any reason behind this?

**Comment by mhubii** [comment]
hi @ardiya, thank you for the feedback. These values are obtained from the CAD model.

Interesting to see there is a discrepancy. When launching the `humble` branch, it seems correct:

![Screenshot from 2023-10-17 12-35-25](https://github.com/lbr-stack/lbr_fri_ros2_stack/assets/26366414/27435470-7792-42cd-a807-f2a9f47976d3)

There, the distance is also `0.035`. Not sure what causes the issue.

**Comment by mhubii** [comment]
Hi @ardiya thank you for the feedback. I think you are right, all other values were obtained from the CAD model but this link.

Will fix!

Thank you very much, great catch!

**Comment by mhubii** [comment]
`0.045` doesn't seem to be right though

**Comment by ardiya** [comment]
Yeah, that's true. Your original `0.035` is the same with the technical drawing of the basic flange though

![image](https://github.com/lbr-stack/lbr_fri_ros2_stack/assets/1798412/7481698d-5905-4aed-8a43-d7f6427f8009)
Based on the measurement in section 4.2.2 of https://www.oir.caltech.edu/twiki_oir/pub/Palomar/ZTF/KUKARoboticArmMaterial/Option_Media_Flange_en.pdf

**Comment by mhubii** [comment]
thank you for sharing, working on fixing this. Will re-export URDF from CAD

**Comment by mhubii** [comment]
could you please pull the latest `noetic` changes and report if it works for you? Thank you again for reporting this issue.

**Comment by ardiya** [comment]
Thanks @mhubii! It works great. Quick question: how do you get the CAD models?
I have different flange and it's difficult to get the Mesh

**Comment by mhubii** [comment]
the CAD models are available on xpert.kuka.com , do you want me to add another model for you that has the correct flange? Please feel free to open a new issue in that case

**Comment by ardiya** [comment]
It's okay, I was able to find `LBR iiwa 14 R820 with media flanges` and able to download it.

@mhubii Do you you http://wiki.ros.org/urdf_from_step to convert step to urdf or is there any package that you recommend to convert it to URDF+mesh file?

**Comment by mhubii** [comment]
Hi @ardiya sorry for coming back so late. Personally, I had access to autodesk fusion 360 at the time and used the URDF exporter https://github.com/syuntoku14/fusion2urdf, that tools works incredibly well
