### ISSUE TITLE
Use of tf2 trees

### ISSUE THREAD

**Issue by Shenwei0** [lbr-stack/lbr_fri_ros2_stack#132]
Do you use tf2 for managing all the coordinate frames, and if so how?

**Comment by mhubii** [comment]
Hi @Shenwei1234 and thank you for the question. When you run the `lbr_bringup` or `lbr_ros2_control` packages, e.g.

```shell
ros2 launch lbr_bringup bringup.launch.py # model specifications / simulation etc.
```

The `joint_state_publisher` and the `robot_state_publisher` nodes will be launched. The `robot_state_publisher` publishes using `tf2`. 

You can find this in the launch files:

- Real robot: https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/f4bed49acd33ed4a8c954638eff83d2f76296dff/lbr_bringup/launch/real.launch.py#L28
- Simulated robot: https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/f4bed49acd33ed4a8c954638eff83d2f76296dff/lbr_bringup/launch/sim.launch.py#L26

A more minimal version of this is in the `lbr_ros2_control` package: https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/humble/lbr_ros2_control/launch/system_interface.launch.py

Hope this answers the question. Let me know if this helps.

**Comment by Shenwei0** [comment]
Thanks for the reply:). If I understand correctly, the joint_state_publisher publishes the robot's joint states using tf2. But to which topic does it publish to, and who is subscribed/listener to the published joint states? Also, what's the difference between joint_state_publisher and robot_state_publisher? What does robot_state_publisher do?

**Comment by mhubii** [comment]
no problem. So the `joint_state_publisher` is part of `ros2_control`. It reads joint states from the hardware and publishes under `/joint_states`.

The `robot_state_publisher` subscribes to `/joint_states`. Given the URDF and joint states, the `robot_state_publisher` computes kinematics and publishes the transforms to `/tf`.

**Comment by Shenwei0** [comment]
I understand now. Thanks again:)

**Comment by mhubii** [comment]
okay great, hopefully it is okay to close this issue for now? Please feel free to ask any other questions or re-open.
