### ISSUE TITLE
Rviz movet planning plugin

### ISSUE THREAD

**Issue by phuicy** [lbr-stack/lbr_fri_ros2_stack#135]
Hi,

I am having issues loading the moveit planning.

The namespace for the robot_description makes it not possible to load it in the display menu.

What am I doing wrong? 

thanks,
Guy

**Comment by mhubii** [comment]
hi @phuicy , could you tell me how you launch the system, what branch you are on etc.

Do you happen to assign the robot a specific name?

Thank you!

**Comment by phuicy** [comment]
Sorry this is my problem, i have now resolved. It was a borked install.

**Comment by mhubii** [comment]
cheers, thank you for coming back @phuicy . Please re-open or create another issue if you encounter other problems.
