### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by mhubii** [lbr-stack/lbr_fri_ros2_stack#149]
Provide a docker file, refer @Nicolai-98 in https://github.com/lbr-stack/lbr_fri_ros2_stack/issues/1#issuecomment-1898038466_

**Comment by Nicolai-98** [comment]
Sure, I can do that. I will clean it up a bit first. You can expect a pull request tomorrow. In addition to the Dockerfile, I also have some scripts for building/launching and creating a new terminal within the Docker container. Would you like me to include them?

**Comment by mhubii** [comment]
yes that would be great, you can just create a pull request against `dev-humble-docker` branch and then we can iterate on it.

But no hurry at all, really appreciate the help!

**Comment by mhubii** [comment]
done in #151
