### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by vazik01** [lbr-stack/lbr_fri_ros2_stack#165]
Hello, I need the documentation for the specified repository. Could you please provide another link for that?

**Comment by mhubii** [comment]
hi @vazik01, will work on updating the documentation this week.

There is documentation here: https://lbr-stack.readthedocs.io/en/latest/, but it is outdated. Thank you for raising the issue. Expect updated documentation this week.

Sorry just realized the link in the readme is broken.

Documentation will be updated as part of #147 

Is there anything I can quickly help you with?
