### ISSUE TITLE
Node Documentation Missing

### ISSUE THREAD

**Issue by CameronDevine** [lbr-stack/lbr_fri_ros2_stack#168]
I have seen high level documentation for this repository, but I have not been able to find any documentation of the nodes. This is necessary for the JOSS review (openjournals/joss-reviews#6138).

**Comment by mhubii** [comment]
thanks for this hint. The documentation is indeed outdated. Refers to #147

**Comment by mhubii** [comment]
documentation is updated in #147 . Please note that this repo does **not** implement a node. This is a general confusion with `ros2_control`. You can find in-depth documentation here: https://lbr-stack.readthedocs.io/en/latest/lbr_fri_ros2_stack/lbr_fri_ros2/doc/lbr_fri_ros2.html
