### ISSUE TITLE
Potential Error in CommandGuard

### ISSUE THREAD

**Issue by StephanSchwarz96** [lbr-stack/lbr_fri_ros2_stack#175]
Hello everyone,

I recently run into some issues with the received robot state data which lead me to digging into the lbr_fri_ros2 package. I am not sure, but i might found an error within the code in command_guard.cpp in line 53: 
```cpp
for (std::size_t i = 0; i < lbr_command.joint_position[i]; ++i) {
```

Unlike the other checks (for position or torque limits), this does not iterate over the size() but the value, which in my case always stops after the first iteration since my joint_1 was lower than 1. Am I missing something here?

Thanks for feedback :)

**Comment by mhubii** [comment]
oh this looks fishy :O, where in the code can this be found?

**Comment by mhubii** [comment]
thank you so much for sharing this @StephanSchwarz96 . This is now fixed, please pull the changes.

There are some changes on the way, which will make this system a bit more capable.

**Comment by mhubii** [comment]
closing this for now as resolved. Thank you again very much! Please feel free to reach out if you have any questions / re-open the issue etc

**Comment by mhubii** [comment]
hi @StephanSchwarz96 , this should now be fully resolved. Let me know if you have any other questions

If you could give some feedback on whether it works well now, that would be awesome, too!
