### ISSUE TITLE
Timeout before FRI connection

### ISSUE THREAD

**Issue by Enzo-let** [lbr-stack/lbr_fri_ros2_stack#205]
I have set the ip like below.  And it can ping the ip of iiwa 14 robot by x66. But when I run the demo, it didn't work. About fri , I think it's 1.15.  I forgot to say i'm using the docker in ubuntu22.04(not VM). I run all them in docker.
I put the problem images below. I hope i can get your response. Thank you very much!!
![3a90e507626aa45ef01a124146cde26](https://github.com/user-attachments/assets/5853e9cf-aee0-4610-b22a-28f7808f8f76)
![7e4bc653c3d59b909c0dda178bd2b2e](https://github.com/user-attachments/assets/9c3902e2-da47-4299-aaff-ac0c7449bd6e)
![65effc19264ac21fbc2f4b937e6e476](https://github.com/user-attachments/assets/c6010a2e-ee1d-451f-9636-0ed04bb690c8)
![be76b5ff6529d744bf02f2c943eb418](https://github.com/user-attachments/assets/044f9aad-0029-4fca-a713-bc0add44a6ca)
![eba40fb0567b98c0553e0678ffd4a1c](https://github.com/user-attachments/assets/94496471-ef1a-4bd2-9298-bca980bb33bd)

**Comment by mhubii** [comment]
hi @Enzo-let , thanks for the detailed pictures. Looks all good.

Docker should work well, but I'll double check. Did you follow these steps:

https://lbr-stack.readthedocs.io/en/latest/lbr_fri_ros2_stack/docker/doc/docker.html

A well known issue is the firewall, maybe check https://github.com/lbr-stack/lbr_fri_ros2_stack/issues/67#issuecomment-1479794623

**Comment by Enzo-let** [comment]
I really appreciate that you answer me. I have found  the problem and resolved it. It’s not the problem of the fire well. I checked the fri version again. I thought it’s 1.15. But i still tried to change the version of fri. And it worked. I don’t know why. Maybe it’s not 1.15. And i want to say thank you again. You have created a really good project.

**Comment by mhubii** [comment]
happy to hear that! KUKA's versioning is not as reliable somehow
