### ISSUE TITLE
FRI I/O GROUPS

### ISSUE THREAD

**Issue by Enzo-let** [lbr-stack/lbr_fri_ros2_stack#208]
Hello, I have a question that  can i use the FRI I/O groups to connect with the end-effector in iiwa14. I wanna control the end-effector by ros2 through the I/O.  I am expecting you can give me some suggestions. Thank you very much.

**Comment by mhubii** [comment]
hit @Enzo-let this is related to #198. Hope it is okay to close this issue in favor for the existing.

The IO is currently not implemented, but has high priority.
