### ISSUE TITLE
Support multiple robots

### ISSUE THREAD

**Issue by mhubii** [lbr-stack/lbr_fri_ros2_stack#21]
Investigate support for multiple robots.

- IP and Port: The robot's IP address and port, that this interface tries to connect to are specified in [fri_hardware_interface.hpp](https://github.com/KCL-BMEIS/lbr_fri_ros2_stack/blob/0d2cc6e2f6bcfbff860fa87ecb87a64520f55181/lbr_hardware/include/lbr_hardware/fri_hardware_interface.hpp#L79). These are set as parameters in the [lbr.ros2_control.xacro](https://github.com/KCL-BMEIS/lbr_fri_ros2_stack/blob/0d2cc6e2f6bcfbff860fa87ecb87a64520f55181/lbr_description/ros2_control/lbr.ros2_control.xacro#L3). The hardware interface is loaded as plugin and has thus access to these parameters. Check access of these parameters through launch files.

- Namespaces: Check the namespaces

**Comment by TheMipmap** [comment]
Hi @mhubii, 

Really looking forward to this enhancement!

My group and I, at Aalborg University, are currently working on implementing two Kuka IIWA 7s on a 'torso'. As such, the support for multiple arms is a necessity for us. :)

So far, we have made a custom URDF, with the torso and both of the robots and reconfigured moveit with the setup assistant. Sadly, however, even though the simulation shows the correct URDF with both robots, it cannot plan trajectories for any of them. 

It would be highly appreciated if you could give us a few pointers as to what need to be changed in order for two robots to work concurrently.

**Comment by mhubii** [comment]
Hi @TheMipmap and sorry for the late response. This is actually functioning now. 

I can respond in more detail tomorrow. But in essence you can 

- connect the two robots to a switch
- in sunrise workbench, you configure a unique IP address for each robot
- in your Java application, you assign one robot port ID 30200 and the other robot 30201

when you launch this stack, you can amend the launch with port_id:=30201.

With regard to moveit, it somehow  has issues with namespacing multiple robots. But we can chat about that

**Comment by mhubii** [comment]
Supported since #121. Will open new issues indicating necessary documentation and the issues regarding moveit in multi-robot tomorrow

**Comment by TheMipmap** [comment]
Thanks for the reply @mhubii! 

Looking forward to the documentation regarding a multi-robot setup! :)

I will try setting it up with the method you described above. If you have time, a detailed description of the moveit part, would be appreciated! :)

**Comment by mhubii** [comment]
May I kindly ask you to open a new issue regarding missing documentation? That would be great. Thank you for the help @TheMipmap

**Comment by TheMipmap** [comment]
Of course, I'll do that! :)

**Comment by mhubii** [comment]
Closing this issue for now as introduced in #121. Added issue #131 for documentation etc
