### ISSUE TITLE
control kuka with velocity control

### ISSUE THREAD

**Issue by shz111** [lbr-stack/lbr_fri_ros2_stack#211]
Hello, I have a question about the control module that if i can use twist_controller like ros1 or the move_servo to velocity control instead position control cause i wanna make the end-effector move along straight line.  I am expecting you can give me some suggestions. Thank you very much!

**Comment by mhubii** [comment]
Hi @shz111 , sorry for the late response. This is a common issue and is currently missing here.

There might be `ros2_controllers` that compute joint velocities from twists, which could be used, but it would be helpful to add this here.

**Comment by mhubii** [comment]
Hi @shz111, MoveIt servo is now added, see doc: https://lbr-stack.readthedocs.io/en/latest/lbr_fri_ros2_stack/lbr_demos/lbr_moveit/doc/lbr_moveit.html#moveit-servo

One issue, the PID here:

https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/95ffd41ce48267c2fda8e192ddd39a4039616ced/lbr_ros2_control/config/lbr_system_parameters.yaml#L10

Makes the real system move rather slow at the moment. This remains to be sorted.
