### ISSUE TITLE
Velocity limit seems too high

### ISSUE THREAD

**Issue by cmower** [lbr-stack/lbr_fri_ros2_stack#35]
The velocity limit defined in the URDF seems too high.

https://github.com/KCL-BMEIS/lbr_fri_ros2_stack/blob/d73115b9f088395b62cfc0073cf1d0ca6aa21c1e/lbr_description/urdf/med7/med7_description.urdf.xacro#L10

Perhaps this is in degrees/sec? The [unit for the velocity limit should be in rad/sec](http://wiki.ros.org/urdf/XML/joint#Elements). For ease in setting joint limit constraints in optas, we should tune the velocity limit.

**Comment by mhubii** [comment]
great catch indeed. The velocity limits should be extracted and tested in the same fashion as masses, refer to https://github.com/KCL-BMEIS/lbr_fri_ros2_stack/blob/foxy/lbr_description/test/test_urdf.py

We should also double check position limits in these files again.

**Comment by mhubii** [comment]
addressed in #69 #70 , to be moved to `foxy` `galactic` `noetic` `melodic`

**Comment by mhubii** [comment]
addressed in #72 #73 , `noetic` and `melodic` missing
