### ISSUE TITLE
Make moveit optional in launch

### ISSUE THREAD

**Issue by cmower** [lbr-stack/lbr_fri_ros2_stack#60]
Note for later when we come to re-vamping the launch sequence. Moveit (below) should be made optional. 

https://github.com/KCL-BMEIS/lbr_fri_ros2_stack/blob/d1e70a7a1160ea2d3f29203b6ab83e2919292c29/lbr_bringup/launch/lbr_bringup.launch.py#L79-L99

**Comment by mhubii** [comment]
Added in #96

**Comment by mhubii** [comment]
closed in #96 for `humble` (not planned for `foxy` / `galactic`). Will be added for `rolling`
