### ISSUE TITLE
KCL Sharepoint

### ISSUE THREAD

**Issue by m1541** [lbr-stack/lbr_fri_ros2_stack#61]
Hi,

Is there any alternative for accessing the files? The sharepoint requires KCL credentials to log in.

**Comment by mhubii** [comment]
Hi @m1541, no sorry, I am afraid these documents are confidential.

You can find them  alternatively on [https://xpert.kuka.com](https://xpert.kuka.com)

**Comment by gianmarco96** [comment]
What version of FRI is required to run the server? We have version 1.11 but that does not seem to work
