### ISSUE TITLE
FRI connection fails for ros noetic

### ISSUE THREAD

**Issue by RaquelMotzfeldtTirach** [lbr-stack/lbr_fri_ros2_stack#67]
Hello, 
First of all thank you for this repo, it looks really interesting and exciting! 

We have gone through the setup, using the noetic branch, but unfortunately encountered a few issues. We have a LBR iiwa 14, to which we have added the FRI package and the LBRserver java file in the src folder. The install and sync went well. 
We then connected our client PC which runs on ubuntu 20.04 and with ros Noetic to the controller through the two possibilities: 
- the X66 port and using 172.31.1.148 as IP, rate of 10ms
- the KONI port and using 192.170.10.1 as IP, rate of 10ms

In both cases, we are able to ping the controller but unable to create a connection. 
We first start the LBRserver application on the SmartPad (rate 10ms, Position Control) and then we run on the client PC the moveit_planning_execution.launch, but the LBRserver stops pretty quickly after not getting any response from the client PC with a "timout before FRI connection was good or excellent" error. 
We used wireshark to have a look at the UDP communication, and we can clearly see that the controller is sending packages but our client PC is not responding. 
![Screenshot from 2023-03-17 16-59-28](https://user-images.githubusercontent.com/93975644/225956532-7da9bc0d-688a-440d-8dc1-9408d05073db.png)

The outcome is the same for both ports/IPs. 

Are we missing something? We are not a part of your university, so we do not have access to your sharepoint.

**Comment by mhubii** [comment]
happy to chat in person if that is the case. We stopped development of the noetic branch, however, it should still work.

When you launch `roslaunch lbr_moveit moveit_planning_execution.launch model:=iiwa14 sim:=false`, did you set `sim:=false`?

**Comment by RaquelMotzfeldtTirach** [comment]
I'm sorry to hear about that, we hope this is not too much trouble then. 
Yes we did indeed change the sim argument to false.

**Comment by mhubii** [comment]
can you find any errors in the terminal, ie `... | grep ERROR` for a quick check

**Comment by mhubii** [comment]
the most common issue are missing dependencies

**Comment by RaquelMotzfeldtTirach** [comment]
The only error I get the launch file terminal is the following: 
**[ERROR] [1679319207.644945605]: Could not find the planner configuration 'None' on the param server**

**Comment by RaquelMotzfeldtTirach** [comment]
Ran `rosdep install --from-paths src --ignore-src -r -y` again and a few (moveit, xacro, joint-trajectory-controller) by hand, but all was already installed.

**Comment by RaquelMotzfeldtTirach** [comment]
![20230320_143751](https://user-images.githubusercontent.com/93975644/226358603-b7918578-bea9-48bb-af80-779fe78bfc4f.jpg)
![20230320_143743](https://user-images.githubusercontent.com/93975644/226358610-fda7c14c-4215-482f-90dc-46fedd4d128b.jpg)

**Comment by mhubii** [comment]
thanks for the feedback. Is this related to #68 ?

may I also ask what version of the FRI you are using?

**Comment by RaquelMotzfeldtTirach** [comment]
I am unsure if this is related, the error is similar but not identical. But it's a connection problem too. 

We have FRI 1.14.0

**Comment by mhubii** [comment]
this repository is built using FRI 1.15, maybe there might be an issue

**Comment by RaquelMotzfeldtTirach** [comment]
That might explain it indeed. Any idea if KUKA will let us update it? It's quite old and not supported anymore I believe

**Comment by mhubii** [comment]
there is probably not a lot that has to be changed to get it running for 1.14, but since we don't own 1.14, it is difficult for me to do this.

Potential changes are to be made here
https://github.com/kCL-BMEIS/fri/tree/ros2-fri-1.15

and in the server app
https://github.com/KCL-BMEIS/lbr_fri_ros2_stack/blob/noetic/server/fri_ros/LBRServer.java

**Comment by RaquelMotzfeldtTirach** [comment]
But even if the FRI version is too old, shouldn't I see in Wireshark some udp msg from my PC towards the robot controller? 
I looks like the problem is on the client PC end no?

**Comment by mhubii** [comment]
the client sends responses, if it never receives anything (for whatever reason), it won't send anything

**Comment by RaquelMotzfeldtTirach** [comment]
Yes but the UDP messages from the controller do arrrive, maybe with the wrong format then?

**Comment by mhubii** [comment]
it could be that from fri `1.14` -> `1.15` there is a new message field, I am trying to look this up right now

**Comment by mhubii** [comment]
May I ask for your help? I can't access the cpp source code for the FRI 1.14. You can extract it through 

![fri_ros_debug](https://user-images.githubusercontent.com/26366414/226381510-62ee51fb-5c33-410b-a638-ca97e19f4279.PNG)

You should see the source code here

![fri_ros_debug_source](https://user-images.githubusercontent.com/26366414/226381694-a156ae34-9905-4b01-bf9d-f00538654a96.PNG)

In the `.zip` file, check there is a license stating

```
Redistribution and use of the software in source and binary forms, with or
without modification, are permitted
```

If you could send me that zip file to `martin.huber@kcl.ac.uk`, I am happy to investigate. If this too much of a burden for you, no problem

**Comment by RaquelMotzfeldtTirach** [comment]
Absolutely no problem, I'll gladly help out! Give me a minute, have to change OS

**Comment by mhubii** [comment]
okay so on the client source side there are absolutely no differences

**Comment by RaquelMotzfeldtTirach** [comment]
So it has to be on the client PC the problem comes from?

**Comment by mhubii** [comment]
possibly. I just ran the `noetic` branch and it runs well

**Comment by RaquelMotzfeldtTirach** [comment]
Shoot ... so something with my setup on the PC or something with the connection is not right. Might also be the iiwa itself ... this repo only uses the FRI package?

**Comment by mhubii** [comment]
you can check whether the fri runs stand alone. E.g. build and install it

https://github.com/KCL-BMEIS/fri/tree/fri-1.14#cross-platform-build-and-installation

run one of the example applications

https://github.com/KCL-BMEIS/fri/tree/fri-1.14#client-side---laptop

**Comment by RaquelMotzfeldtTirach** [comment]
Followed the instructions, the build on the client PC worked fine. Even got the applications (LBRJointSineOverlay, and so on) to appear on the iiwa. 
Tried connecting, but it failed. But this time the IP address is not correct: the smartPad shows "creating connection to 127.0.01". 
Did this installation change the FRI IP in the settings?

**Comment by mhubii** [comment]
the LBRJointSineOverlay sample application, by default (you'd have to check in Sunrise), sets the ip to 127.0.0.1

So you'd have to change this to your IP and synchronize with the kuka controller. But it would be surprising if this example worked (given this repository doesn't work)

**Comment by RaquelMotzfeldtTirach** [comment]
I'm about to test it.

**Comment by RaquelMotzfeldtTirach** [comment]
Unfortunately, even now with the right IP, it does not work

**Comment by RaquelMotzfeldtTirach** [comment]
I'll redo the sunrise project setup from scratch following https://github.com/KCL-BMEIS/fri/tree/fri-1.14#server-side---kuka-controller to be sure

**Comment by mhubii** [comment]
sorry to hear that. The instructions might differ a little bit for your robot

**Comment by RaquelMotzfeldtTirach** [comment]
Yes, we have a different media flange

**Comment by RaquelMotzfeldtTirach** [comment]
Still not working unfortunately

**Comment by mhubii** [comment]
Really sorry to hear that and no idea what the issue could be.

Maybe it makes sense to try and get the fri running standalone first.

There is also the iiwa_stack https://github.com/IFL-CAMP/iiwa_stack, which you could try. This one uses ros Java on the Kuka controller

**Comment by mhubii** [comment]
I'll take this feedback seriously and will try to improve the unit testing. This particular issue has probably to do with the fri or some network settings

**Comment by RaquelMotzfeldtTirach** [comment]
Thank you for your help, I'll be looking into this and I'll keep you updated

**Comment by mhubii** [comment]
thank you! I'll forward you some FRI documentation

**Comment by RaquelMotzfeldtTirach** [comment]
I think I figured it out: 
Just tried only KUKA's FRI and the connection worked as soon as I disabled my firewall! 
Still have to setup my firewall correctly and try this repo again, but looks promising!

**Comment by RaquelMotzfeldtTirach** [comment]
To setup the firewall on ubuntu 20.04: 
`sudo ufw allow proto udp from 172.31.1.147 to 172.31.1.148 port 30200`

**Comment by RaquelMotzfeldtTirach** [comment]
It all works fine now, thank you for your help !

**Comment by mhubii** [comment]
oh okay so a firewall related issue. Thank you for investigating!
