### ISSUE TITLE
Issue with Med14 in Gazebo

### ISSUE THREAD

**Issue by cmower** [lbr-stack/lbr_fri_ros2_stack#82]
There seems to be an issue with the Med14 model in Gazebo:

![Screenshot from 2023-04-27 13-37-56](https://user-images.githubusercontent.com/8171456/234851121-8d7a2edd-d332-414d-8fbf-8ca74b88a1c1.png)

Rviz seems to be fine though.

**Comment by mhubii** [comment]
please pull the newest changes, this fixes this issue

**Comment by mhubii** [comment]
this issues should be solved, please re-open in case it re-appears
