### ISSUE TITLE
Release mode build

### ISSUE THREAD

**Issue by mhubii** [lbr-stack/lbr_fri_ros2_stack#92]
Might need to add cmake flag for release build or set a default build unless specified, ie `colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release`

**Comment by SamantaTarun** [comment]
@mhubii where do I have to add?

**Comment by mhubii** [comment]
sorry for the late reply! Just saw it. I came across it somewhere else and realized this might be an issue here, too.

You might have to add this during the build, ie when calling `colcon build`

**Comment by SamantaTarun** [comment]
> sorry for the late reply! Just saw it. I came across it somewhere else and realized this might be an issue here, too.
> 
> You might have to add this during the build, ie when calling `colcon build`

May I know that file name or location where I have to make changes.

**Comment by mhubii** [comment]
when you build this repository, you might have to add this as a flag to the build. No file needs changing, but one might add a default build type to the cmake files for the hardware interface and the fri

**Comment by mhubii** [comment]
going to be added in #93

**Comment by mhubii** [comment]
closed in #93
